name: Resourcepack Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Generate
      run: |
        chmod +x generate.sh
        ./generate.sh
        mkdir build
        cp item-models.yml build/
        zip -r ./build/resourcepack.zip ./assets ./pack.mcmeta ./LICENSE
    
    - name: Upload Pack
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Slimefun4-Resourcepack
        path: ./resourcepack.zip
        # The desired behavior if no files are found usi
    
    - name: Upload item-models.yml
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: item-models
        path: ./item-models.yml
        # The desired behavior if no files are found usi
