name: Continuous Deployment
on:
  push:
    branches:
    - master
    
jobs:
  compile-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v1
      - name: Setting up node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Generating Resourcepack
        run: sh compile.sh
      - name: Zipping Resources
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./resourcepack.zip ./pack
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload Resourcepack.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./resourcepack.zip
          asset_name: Slimefun Resourcepack.zip
          asset_content_type: application/zip
      - name: Upload item-models.yml
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./item-models.yml
          asset_name: item-models.yml
          asset_content_type: application/x-yaml
